easy_admin:
    site_name: 'Conferences - first app'
    design:
        menu:
            - { route: 'homepage', label: 'Back to the website', icon: 'home' }
            - { entity: 'Conference', label: 'Conferences', icon: 'map-marker' }
            - { entity: 'Comment', label: 'Comments', icon: 'comments' }
    entities:
        # List the entity class name you want to manage
        Conference:
            class: App\Entity\Conference
        Comment:
            class: App\Entity\Comment
            list:
                fields:
                    - id
                    - author
                    - { property: 'email', type: 'email' }
                    - text
                    - {
                          property: 'createdAt',
                          type: 'datetime',
                          format: 'd/m/Y H:i',
                      }
                sort: ['createdAt', 'desc']
                filters: ['conference']
            edit:
                fields:
                    - { property: conference }
                    - { property: createdAt, type: datetime, type_options: { attr: { readonly: true } } }
                    - author
                    - { property: email, type: email }
                    - text
